### ISSUE TITLE
Class 'Nette\Utils\Arrays' not found in UnusedPublicClassMethodRule

### ISSUE THREAD

**Issue by gemal** [TomasVotruba/unused-public#114]
Im getting this. What am I doing wrong?

```
Exception: Class 'Nette\Utils\Arrays' not found in [/development/vendor/tomasvotruba/unused-public/src/Rules/UnusedPublicClassMethodRule.php, line 86]
2024-04-27 14:05:53 Error: [Error] Class 'Nette\Utils\Arrays' not found in /development/vendor/tomasvotruba/unused-public/src/Rules/UnusedPublicClassMethodRule.php on line 86
Stack Trace:
#0 phar:///development/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(172): TomasVotruba\UnusedPublic\Rules\UnusedPublicClassMethodRule->processNode()
#1 phar:///development/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(136): PHPStan\Command\AnalyseApplication->getCollectedDataErrors()
#2 phar:///development/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(202): PHPStan\Command\AnalyseApplication->analyse()
#3 phar:///development/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute()
#4 phar:///development/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870): _PHPStan_7961f7ae1\Symfony\Component\Console\Command\Command->run()
#5 phar:///development/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_7961f7ae1\Symfony\Component\Console\Application->doRunCommand()
#6 phar:///development/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_7961f7ae1\Symfony\Component\Console\Application->doRun()
#7 phar:///development/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124): _PHPStan_7961f7ae1\Symfony\Component\Console\Application->run()
#8 phar:///development/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_7961f7ae1\{closure}()
```

**Comment by gemal** [comment]
If I manually install `composer require nette/utils` it works

**Comment by staabm** [comment]
Fixed in latest release via https://github.com/TomasVotruba/unused-public/pull/116
